---
Negative island analysis
---
```{r}
rm(list = ls())
library(tidyverse)
library(brms)
library(lme4)
library(lmerTest)
library(plotrix)
library(stringr)
library(readxl)

remove_na = function(x) {
  x[!is.na(x)]
}

d = read_csv("./tests/Clefts/combined_results.csv") %>%
  select(-1, -2) %>%
  mutate(unk=unk == "True") %>%
  separate(condition, sep="_", into=c("subj", "embedding", "verb"))

d_agg = d %>% 
  group_by(model, region, sent_index, subj, embedding, verb) %>% 
    summarise(surprisal=sum(surprisal),
              unk=any(unk)) %>%
    ungroup() %>% 
  filter(!unk) 



```


### Post-gap material



```{r}
d_agg_cont = d_agg %>%
  filter(region == "continuation")

d_agg_cont = d_agg_cont %>%
  mutate(agreement = apply( d_agg_cont[ , c('subj','verb') ] , 1 , paste , collapse = "-" )) %>%
  select(-subj, -verb) 

d_agg_cont %>% 
  ggplot(aes(x=embedding, y=surprisal, fill=agreement)) +
    geom_boxplot(position="dodge") +
  ylab("Surprisal") +
    xlab("Level of embedding") +
  theme_bw(base_size=20) + 
    facet_wrap(~model) +
  ggsave("~/Desktop/agr-sur_cls.eps",height=8,width=8)


d_agg_cont$embedding <- factor(d_agg_cont$embedding)
levels(d_agg_cont$embedding)[levels(d_agg_cont$embedding)=="l1"] <- "1"
levels(d_agg_cont$embedding)[levels(d_agg_cont$embedding)=="l2"] <- "2"
levels(d_agg_cont$embedding)[levels(d_agg_cont$embedding)=="l3"] <- "3"
levels(d_agg_cont$embedding)[levels(d_agg_cont$embedding)=="l4"] <- "4"



d_agg_cont %>% 
  ggplot(aes(x=agreement, y=surprisal, fill =embedding)) +
    geom_boxplot(position="dodge") +
  ylab("Surprisal") +
    xlab("") +
  theme_bw(base_size=18) + 
  theme(legend.position = "none") +
    facet_wrap(~model) +
ggsave("~/Desktop/agr-sur_cls.eps",height=8,width=8.5)

  
```

```{r}

m = "gulordava"

c = d_agg_cont %>%
    filter(agreement == "npl-vpl" | agreement == "nsg-vsg", embedding == "l1" ,  model == m)

t.test(c$surprisal ~ c$agreement)  
c$agreement <- factor(c$agreement)
boxplot(c$surprisal ~ c$agreement)    

c = d_agg_cont %>%
    filter(agreement == "npl-vpl" | agreement == "nsg-vsg", embedding == "l2", model == m)

t.test(c$surprisal ~ c$agreement)  
c$agreement <- factor(c$agreement)
boxplot(c$surprisal ~ c$agreement)    

c = d_agg_cont %>%
    filter(agreement == "npl-vpl" | agreement == "nsg-vsg", embedding == "l3", model == m)

t.test(c$surprisal ~ c$agreement)  
c$agreement <- factor(c$agreement)
boxplot(c$surprisal ~ c$agreement)   

###

c = d_agg_cont %>%
    filter(agreement == "npl-vpl" | agreement == "nsg-vpl", embedding == "l1" ,  model == m)

t.test(c$surprisal ~ c$agreement)  
c$agreement <- factor(c$agreement)
boxplot(c$surprisal ~ c$agreement)    

c = d_agg_cont %>%
    filter(agreement == "npl-vpl" | agreement == "nsg-vpl", embedding == "l2", model == m)

t.test(c$surprisal ~ c$agreement)  
c$agreement <- factor(c$agreement)
boxplot(c$surprisal ~ c$agreement)    

c = d_agg_cont %>%
    filter(agreement == "npl-vpl" | agreement == "nsg-vpl", embedding == "l3", model == m)

t.test(c$surprisal ~ c$agreement)  
c$agreement <- factor(c$agreement)
boxplot(c$surprisal ~ c$agreement)   


```
